apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: explorer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: explorer
  minReplicas: 5
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20