apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  template:
    spec:
      containers:
        - name: explorer
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
            requests:
              cpu: 50m
              memory: 128Mi
