apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: klever-explorer
commonLabels:
  branch: development
  env: dev
patchesStrategicMerge:
- web-server.yaml
resources:
  - hpa.yaml
bases:
  - ../base/