apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  template:
    spec:
      nodeSelector:
        role: common
      containers:
      - name: explorer
        resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            cpu: 100m
            memory: 128Mi
