apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: web-server
  name: explorer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web-server
    spec:
      containers:
        - name: explorer
          image: klever-explorer
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: docker-klever-explorer
      nodeSelector:
        role: common
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: web-server
  name: explorer
spec:
  selector:
    app.kubernetes.io/component: web-server
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: 3000
