name: Build

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone America/Sao_Paulo

      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build
